export const PerguntasPP = () => {
    const questoes = 'Meu trabalho precisa ser perfeito para que eu fique satisfeito.'
        + '*Sou extremamente sensível aos comentários dos outros.'
        + '*Geralmente digo às pessoas quando seu trabalho não está à altura dos meus padrões.'
        + '*Sou bem organizado.'
        + '*Reflito cuidadosamente sobre minhas opções antes de tomar uma decisão.'
        + '*Se eu cometer erros, as pessoas irão fazer pouco de mim.'
        + '*Sempre senti pressão do(s) meu(s) pai(s) para ser o melhor.'
        + '*Se eu fizer alguma coisa menos do que perfeita, terei dificuldade em superar isso.'
        + '*Toda minha energia é empregada na obtenção de um sucesso impecável.'
        + '*Comparo meu trabalho com o de outros e frequentemente me sinto inadequado.'
        + '*Fico incomodado quando as outras pessoas não mantêm os mesmos padrões que eu.'
        + '*Penso que as coisas devem ser guardadas em seus lugares.'
        + '*Eu me pego planejando muitas das minhas decisões.'
        + '*Fico particularmente constrangido com um fracasso.'
        + '*Meus pais me exigiam padrões elevados.'
        + '*Passo muito tempo me preocupando com coisas que fiz ou com coisas que preciso fazer.'
        + '*Não tolero fazer as coisas pela metade.'
        + '*Sou sensível ao modo como os outros respondem ao meu trabalho.'
        + '*Não sou muito paciente com as desculpas das pessoas por um trabalho mediocre.'
        + '*Eu me caracterizaria como uma pessoa organizada.'
        + '*A maioria das minhas decisões é tomada depois que tive tempo para pensar a respeito.'
        + '*Reajo de forma exagerada quando cometo erros.'
        + '*Meu(minha) pai(mãe) é(são) difícil(eis) de agradar.'
        + '*Se cometo um erro, meu dia inteiro está arruinado.'
        + '*Tenho que ser o melhor em todas as tarefas que realizo.'
        + '*Preocupo-me se outras pessoas irão aprovar minhas ações.'
        + '*Geralmente sou crítico com as outras pessoas.'
        + '*Gosto de ser sempre organizado e disciplinado.'
        + '*Geralmente preciso refletir sobre as coisas antes de saber o que quero.'
        + '*Se alguém aponta um erro que cometi, sinto que de certa forma perdi o respeito dessa pessoa.'
        + '*Meu(minha) pai(mãe) te(ë)m altas expectativas quanto ao desempenho.'
        + '*Se digo ou faço alguma coisa idiota tendo a ficar pensando nisso o resto do dia.'
        + '*Oriento minhas ações com rigor para atingir padrões elevados.'
        + '*Frequentemente não falo nada porque temo dizer a coisa errada.'
        + '*Frequentemente fico irritado com o trabalho preguiçoso ou desleixado de outras pessoas.'
        + '*Limpo minha casa com frequência.'
        + '*Preciso de tempo para montar um plano e agir.'
        + '*Se eu estragar alguma coisa, as pessoas podem começar a questionar tudo o que faço.'
        + '*Durante meu crescimento, senti muita pressão para fazer tudo certo.'
        + '*Quando cometo um erro, geralmente não consigo parar de pensar nisso.'
        + '*Preciso atingir a excelência em tudo o que faço.'
        + '*Sou inseguro sobre o que os outros pensam de mim.'
        + '*Tenho pouca tolerância com os erros de pessoas negligentes.'
        + '*Não deixo de guardar as coisas assim que termino de usá-las.'
        + '*Tendo a deliberar antes de tomar minha decisão.'
        + '*Para mim, um erro é igual a fracasso.'
        + '*Meu(minha) pai(mãe) me pressiona(m) muito para que tenha sucesso.'
        + '*Com frequência fico obcecado com alguma coisa que fiz.'
        + '*Frequentemente me preocupo que as pessoas possam entender errado o que eu digo.'
        + '*Frequentemente fico frustrado com os erros das outras pessoas.'
        + '*Meu guarda-roupa é limpo e organizado.'
        + '*Geralmente não tomo decisões na hora.'
        + '*Cometer erros é um sinal de burrice.'
        + '*Sempre achei que meu(s) pai(mãe) queria(m) que eu fosse perfeito.'
        + '*Depois que entrego um projeto, não consigo parar de pensar em como poderia ter feito melhor.'
        + '*Meu espaço de trabalho é organizado em geral.'
        + '*Se cometo um erro grave, sinto-me uma pessoa sem importância.'
        + '*Meu(s) pai(mãe) esperava(m) de mim nada menos que o melhor.'
        + '*Passo boa parte do tempo preocupado com a opinião que outras pessoas têm de mim.';

    return questoes.split('*');
}

